# Generated by Django 4.0.5 on 2022-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAlbum', models.CharField(max_length=50)),
                ('anoLanc', models.CharField(max_length=4)),
                ('upVotes', models.IntegerField(default=0)),
                ('downVotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloMusica', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=10)),
                ('compositor', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArtista', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=50)),
                ('anoEstreia', models.CharField(max_length=4)),
                ('albuns', models.ManyToManyField(to='notMusic.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='musicas',
            field=models.ManyToManyField(to='notMusic.musica'),
        ),
    ]
