# Generated by Django 4.0.5 on 2022-06-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notMusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='linkImg',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
