# Generated by Django 4.0.5 on 2022-06-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notMusic', '0002_album_linkimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='linkMusica',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
