# Generated by Django 4.0.5 on 2022-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notMusic', '0004_artista_fotoartista'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='fotoMusica',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
